### ISSUE TITLE
This socket has been ended by the other party

### ISSUE THREAD

**Issue by baccaristic** [botkalista/ayaya-league-chat-proxy#1]
Hello , sorry for opening this , but each time I run league after starting the proxy it crash and give this error output:
Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
    at PassThrough.<anonymous> (ayaya-league-chat-proxy-main\ayaya-league-chat-proxy-main\src\components\ChatProxy.ts:23:63)
    at PassThrough.emit (events.js:315:20)
    at PassThrough.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at PassThrough.Readable.push (internal/streams/readable.js:223:10)
    at PassThrough.Transform.push (internal/streams/transform.js:166:32)
    at PassThrough.afterTransform (internal/streams/transform.js:101:10)
    at PassThrough._transform (internal/streams/passthrough.js:46:3)

am I doing something wrong?
Thanks and sorry again!

**Comment by botkalista** [comment]
> Hello , sorry for opening this , but each time I run league after starting the proxy it crash and give this error output:
> Error: This socket has been ended by the other party
> at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
> at PassThrough. (ayaya-league-chat-proxy-main\ayaya-league-chat-proxy-main\src\components\ChatProxy.ts:23:63)
> at PassThrough.emit (events.js:315:20)
> at PassThrough.EventEmitter.emit (domain.js:467:12)
> at addChunk (internal/streams/readable.js:309:12)
> at readableAddChunk (internal/streams/readable.js:284:9)
> at PassThrough.Readable.push (internal/streams/readable.js:223:10)
> at PassThrough.Transform.push (internal/streams/transform.js:166:32)
> at PassThrough.afterTransform (internal/streams/transform.js:101:10)
> at PassThrough._transform (internal/streams/passthrough.js:46:3)
> 
> am I doing something wrong?
> Thanks and sorry again!

What region are you ? and what OS ?

**Comment by baccaristic** [comment]
> > Hello , sorry for opening this , but each time I run league after starting the proxy it crash and give this error output:
> > Error: This socket has been ended by the other party
> > at TLSSocket.writeAfterFIN [as write] (net.js:456:14)
> > at PassThrough. (ayaya-league-chat-proxy-main\ayaya-league-chat-proxy-main\src\components\ChatProxy.ts:23:63)
> > at PassThrough.emit (events.js:315:20)
> > at PassThrough.EventEmitter.emit (domain.js:467:12)
> > at addChunk (internal/streams/readable.js:309:12)
> > at readableAddChunk (internal/streams/readable.js:284:9)
> > at PassThrough.Readable.push (internal/streams/readable.js:223:10)
> > at PassThrough.Transform.push (internal/streams/transform.js:166:32)
> > at PassThrough.afterTransform (internal/streams/transform.js:101:10)
> > at PassThrough._transform (internal/streams/passthrough.js:46:3)
> > am I doing something wrong?
> > Thanks and sorry again!
> 
> What region are you ? and what OS ?

I'm on EUW and I'm running on Windows 10

**Comment by baccaristic** [comment]
Any update ?

**Comment by baccaristic** [comment]
UPDATE:
Now I'm getting this as Output 
![image](https://user-images.githubusercontent.com/78027050/120213961-22087680-c234-11eb-8db3-e34b9c8fc6d8.png)

it's just stuck like that and same for league client not loading chat
![image](https://user-images.githubusercontent.com/78027050/120214030-33518300-c234-11eb-9db5-82a50eda3c02.png)

**Comment by botkalista** [comment]
Problem solved. Stop using shitty VALORANT accounts xD
